import type { LoanInputs, LoanResults, FinancialSummary } from './loan';
import { formatCurrency, formatDateLong, formatPercent } from './loan';

export type ScenarioData = {
  inputs: LoanInputs;
  results: LoanResults;
  financial: FinancialSummary;
  name: string;
};

export function generateShareableSummary(data: ScenarioData): string {
  const { inputs, results, financial, name } = data;
  const lines: string[] = [
    `LOAN CALCULATION SUMMARY`,
    `${name}`,
    ``,
    `Loan Amount:       ${formatCurrency(inputs.loanAmount)}`,
    `Interest Rate:     ${inputs.annualInterestRate}% APR`,
    `Loan Term:         ${inputs.loanTermMonths} months`,
    ``,
    `Monthly Payment:   ${formatCurrency(results.monthlyPayment)}`,
    `Total Repayment:   ${formatCurrency(results.totalRepayment)}`,
    `Total Interest:    ${formatCurrency(results.totalInterest)}`,
    `Payoff Date:       ${formatDateLong(results.payoffDate)}`,
  ];

  if (financial.dtiWithNewLoan != null) {
    lines.push(``, `FINANCIAL SUMMARY`);
    if (financial.dtiRatio != null) lines.push(`Current DTI:       ${formatPercent(financial.dtiRatio)}`);
    if (financial.dtiWithNewLoan != null) lines.push(`DTI with loan:     ${formatPercent(financial.dtiWithNewLoan)}`);
    if (financial.remainingIncome != null) lines.push(`Remaining income:  ${formatCurrency(financial.remainingIncome)}/mo`);
  }

  lines.push(``, `Generated by LoanWise on ${formatDateLong(new Date())}`);

  return lines.join('\n');
}

export async function copyToClipboard(text: string): Promise<boolean> {
  try {
    await navigator.clipboard.writeText(text);
    return true;
  } catch {
    try {
      const textarea = document.createElement('textarea');
      textarea.value = text;
      textarea.style.position = 'fixed';
      textarea.style.opacity = '0';
      document.body.appendChild(textarea);
      textarea.select();
      document.execCommand('copy');
      document.body.removeChild(textarea);
      return true;
    } catch {
      return false;
    }
  }
}

export function printReport(): void {
  window.print();
}

export function exportPDF(): void {
  window.print();
}
